---
title: "Mario's Contributions"
author: "Mario Lloyd Galvao-Wilson"
output:
  html_document:
    df_print: paged
---

```{r}
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyr)
genre <- read.csv("./1921_2020_spotify/data_by_genres.csv")
artists <- read.csv("./1921_2020_spotify/data_w_genres.csv")
```

```{r}
top10g <- genre %>% 
  arrange(-popularity) %>%
  head(10)

top10g %>%
  ggplot(aes(genres, popularity)) + geom_col(fill = 'royalblue3') + theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 1, hjust = 1)) + coord_cartesian(ylim = c(70, 82)) + labs(x = 'Top 10 Genres', y = 'Popularity (scaled)', title = 'Popularity of the Top 10 Genres')
```

```{r}
v <- melt(top10g, id.vars = 'genres')
ggplot(v, aes(genres, value)) + geom_col()
```

```{r}
#e <- top10g %>%
  #pivot_longer(., cols = c('acousticness', 'danceability', 'energy', 'instrumentalness', 'liveness', 'loudness', 'tempo', 'valence'), names_to = 'Characteristics', values_to = 'Values') #%>%
  #ggplot(top10g, aes('Characteristics', 'Values')) + geom_col()
```

```{r}
top10g %>%
  select(-duration_ms, -speechiness, -popularity, -mode, -loudness, -tempo, -key) %>%
  pivot_longer(., cols = !genres) %>%
  ggplot(aes(name, value)) + geom_col(position = 'dodge') + facet_wrap(~genres) + coord_flip() + labs(x = 'Value', y = 'Characteristic', title = 'Values for Each Characteristic of Each Top 10 Genre') + theme_bw()
```